-- #1: MAP INCORRECT DIMENSION_2 VALUES TO CORRECT VALUES USING THE MAP TABLE
WITH DIMENSIONS_FIXED AS (SELECT A.DIMENSION_1,
                                 COALESCE(MAP.CORRECT_VALUE, A.DIMENSION_2) AS CORRECTED_DIMENSION_2,
                                 A.MEASURE_1,
                                 A.MEASURE_2
                          FROM A
                          LEFT JOIN MAP ON A.DIMENSION_2 = MAP.WRONG_VALUE),
     -- #2: AGGREGATE MEASURE_1 AND MEASURE_2 FOR DISTINCT PAIRS OF CORRECTED_DIMENSION_1 AND CORRECTED_DIMENSION_2
     AGGREGATION AS (SELECT DF.DIMENSION_1,
                            DF.CORRECTED_DIMENSION_2 AS DIMENSION_2,
                            SUM(DF.MEASURE_1)        AS MEASURE_1,
                            SUM(DF.MEASURE_2)        AS MEASURE_2
                     FROM DIMENSIONS_FIXED DF
                     GROUP BY DF.DIMENSION_1,
                              DF.CORRECTED_DIMENSION_2)
-- FINAL RESULT WITH REPLACED VALUES
SELECT AG.DIMENSION_1,
       AG.DIMENSION_2,
       COALESCE(AG.MEASURE_1, 0) AS MEASURE_1,
       COALESCE(AG.MEASURE_2, 0) AS MEASURE_2
FROM AGGREGATION AG;
